use UNIVER;

----- 1 point -----

select AUDITORIUM.AUDITORIUM[Аудитория],AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Тип аудитории]
	from AUDITORIUM inner join AUDITORIUM_TYPE
		on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	order by AUDITORIUM.AUDITORIUM

----- 2 point -----

select AUDITORIUM.AUDITORIUM[Аудитория], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Тип аудитории]
	from AUDITORIUM inner join AUDITORIUM_TYPE
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and
		AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'
	order by AUDITORIUM.AUDITORIUM

----- 3 point -----

select FACULTY.FACULTY[Факультет], PULPIT.PULPIT[Кафедра], PROFESSION.PROFESSION[Специальность], SUBJECT.SUBJECT[Дисциплина], 
		STUDENT.NAME[Имя студента],
	case
		when(PROGRESS.NOTE = 6) then 'шесть'
		when(PROGRESS.NOTE = 7) then 'семь'
		when(PROGRESS.NOTE = 8) then 'восемь'
		else 'nope'
	end [Оценка]
	from PROFESSION inner join FACULTY 
		on PROFESSION.FACULTY = FACULTY.FACULTY
	inner join PULPIT
		on FACULTY.FACULTY = PULPIT.FACULTY
	inner join SUBJECT
		on SUBJECT.PULPIT = PULPIT.PULPIT
	inner join PROGRESS
		on PROGRESS.SUBJECT = SUBJECT.SUBJECT
	inner join STUDENT
		on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	inner join GROUPS
		on GROUPS.IDGROUP = STUDENT.IDGROUP and GROUPS.PROFESSION = PROFESSION.PROFESSION
	where PROGRESS.NOTE between 6 and 8
	order by PROGRESS.NOTE desc 

----- 4 point -----

select PULPIT.PULPIT[Кафедра], isnull(TEACHER.TEACHER_NAME, '****')[Преподаватель]
	from PULPIT left outer join TEACHER
		on PULPIT.PULPIT = TEACHER.PULPIT
	order by PULPIT.PULPIT
	
----- 5-1 point -----

select isnull(AUDITORIUM.AUDITORIUM, 'No name')[Аудитория], AUDITORIUM.AUDITORIUM_CAPACITY, AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE
	from AUDITORIUM full outer join AUDITORIUM_TYPE
		on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	order by AUDITORIUM.AUDITORIUM

----- 5-2 point -----
		
select AUDITORIUM_TYPE.AUDITORIUM_TYPE, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM_TYPE full outer join AUDITORIUM
		on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	order by AUDITORIUM.AUDITORIUM

----- 5-3 point -----

select isnull(AUDITORIUM.AUDITORIUM, 'No name')[Аудитория], isnull(AUDITORIUM.AUDITORIUM_CAPACITY, 0)[Вместимость], 
		isnull(AUDITORIUM.AUDITORIUM_NAME, '***')[Имя аудитории], isnull(AUDITORIUM.AUDITORIUM_TYPE, '***')[Тип аудитории], 
		isnull(AUDITORIUM_TYPE.AUDITORIUM_TYPE, '***')[Тип аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Название аудитории]
	from AUDITORIUM full outer join AUDITORIUM_TYPE
		on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	order by AUDITORIUM.AUDITORIUM

select isnull(AUDITORIUM.AUDITORIUM, 'No name')[Аудитория], isnull(AUDITORIUM.AUDITORIUM_CAPACITY, 0)[Вместимость], 
		isnull(AUDITORIUM.AUDITORIUM_NAME, '***')[Имя аудитории], isnull(AUDITORIUM.AUDITORIUM_TYPE, '***')[Тип аудитории], 
		isnull(AUDITORIUM_TYPE.AUDITORIUM_TYPE, '***')[Тип аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Название аудитории]
	from AUDITORIUM_TYPE full outer join AUDITORIUM
		on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	order by AUDITORIUM.AUDITORIUM

----- 6 point -----

select AUDITORIUM.AUDITORIUM[Аудитория],AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Тип аудитории]
	from AUDITORIUM cross join AUDITORIUM_TYPE
		where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	order by AUDITORIUM.AUDITORIUM